networks:
  rag_net:
    driver: bridge
version: "3.9"

services:
  app:
    networks:
      - rag_net
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env.prod
    environment:
      - APP_ENV=prod
    depends_on:
      - minio
    volumes:
      - ./app/debug/pages:/app/debug/pages
      - ./app/debug/json:/app/debug/json

  minio:
    networks:
      - rag_net
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    env_file:
      - .env.prod

volumes:
  minio_data:
