networks:
  rag_net:
    driver: bridge
version: "3.9"

services:
  app:
    networks:
      - rag_net
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    env_file:
      - .env
    environment:
      - APP_ENV=development
      - RUN_MIGRATIONS_ON_START=true
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8000/health" ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s
    volumes:
      - ./app/debug/pages:/app/debug/pages
      - ./app/debug/json:/app/debug/json

  minio:
    networks:
      - rag_net
    image: minio/minio
    command: server /data --console-address ":9001"
    ports:
      - "9000:9000" # S3 API
      - "9001:9001" # Web UI
    volumes:
      - minio_data:/data
    env_file:
      - .env

volumes:
  minio_data:
